---
- hosts: api01
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: "run rolling deployment bash script"
      command: "sh /opt/deploy"
